config/routes.rb
Rails.application.routes.draw do
  root controller: :index, action: :index
  resources :index, only: [:create, :index]
  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index, :show], constraints: { format: 'json' }
    end
  end
  resources :articles, shallow: true do
    resources :comments, only: [:new, :create, :show]
  end
  resources :categories, only: [:show]
  devise_for :users
  resources :subscriptions, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :body, :categories
  has_many :comments
  has_and_belongs_to_many :categories
  has_one_attached :image
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :body
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_default_role, if: :new_record?

  enum role: [:visitor, :author, :subscriber, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private

  def set_default_role
    self.role ||= :visitor
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController

  def index
    articles = Article.all
    render json: articles
  end

  def show
    article = Article.find(params[:id])
    render json: article
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    redirect_to root_path, notice: 'Aja baja!'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article_and_category, except: [:create]

  def new
    @article = Article.new
    authorize @article
  end

  def show
    @categories = Category.all
    authorize @article
  end


  def create
    params[:article][:categories].shift
    @article = Article.new(article_params)
    authorize @article
    @article.image.attach(params[:article][:image])
    add_categories_to_article
    if @article.save
      flash[:success] = 'Article successfully created'
      redirect_to article_path(@article)
    else
      flash[:error] = error_message(@article)
      redirect_to new_article_path
    end
  end

  def destroy
    authorize @article
    @article.destroy
    flash[:success] = "#{@article.title} has been deleted"
    redirect_to root_path
  end

  def update
    authorize @article
    params[:article][:categories].shift
    @article.image.attach(params[:article][:image]) if params[:article][:image]
    add_categories_to_article
    if @article.update(article_params)
      flash[:success] = 'Article successfully updated'
      redirect_to article_path(@article)
    else
      flash[:error] = error_message(@article)
      render 'edit'
     end
  end

  private

  def add_categories_to_article
    categories = params[:article][:categories]
    categories.each do |category_id|
      category = Category.find_by(id: category_id)
      @article.categories.include?(category) ? next : @article.categories << category
    end
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def find_article_and_category
    @article = Article.find_by(id: params[:id])
    @categories = Category.all
  end

  def error_message(article)
    output = ''
    article.errors.full_messages.each do |error|
      output += "#{error} "
    end
    output
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(id: params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params.merge(article_id: params[:article_id]))
    if @comment.save
      flash[:success] = 'Comment posted successfully'
      redirect_back(fallback_location: root_path)
    else
      flash[:error] = @comment.errors.full_messages.first
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :article_id)
  end
end

app/controllers/index_controller.rb
require 'news-api'
class IndexController < ApplicationController
  def index
    news_api_client = News.new(Rails.application.credentials.news[:news_api_client])
    @api_news_feed = news_api_client.get_top_headlines(category: 'technology', country: 'us', pageSize: 5)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 10000,
      description: 'DreamTeam Publications Monthly Subscription',
      currency: 'sek'
    )

    if charge.paid?
      current_user.subscriber = true
      current_user.save
      redirect_to root_path, notice: 'You are now subscribed!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fake_location
    ({coords: Rails.application.config.try(:fake_location).try(:to_hash)}).to_json
  end
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with model: @article, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, value: @article.title %>
  <% if @article.image.attachment %>
    <%= image_tag @article.image, width: '250' %>
  <% end %>
  <%= form.file_field :image %>
  <%= form.label :content %>
  <%= form.text_area :body, id: 'article_content', value: @article.body %>
  <%= form.label :categories %>
  <%= form.select(
                  :categories,
                  @categories.collect {|category| [ category.name, category.id ]},
                  {},
                  { multiple: true, id: 'categories' })
  %>
  <%= form.submit value: 'Submit Changes' %>
<% end %>

app/views/articles/new.html.erb
<%= form_with model: Article.new, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: 'Title' %>
  <%= form.file_field :image %>
  <%= form.label :content %>
  <%= form.text_area :body, placeholder: 'Content' %>
  <%= form.label :categories %>
  <%= form.select(
                  :categories,
                  @categories.collect {|category| [ category.name, category.id ]},
                  {},
                  { multiple: true, id: 'categories' })
  %>
  <%= form.submit value: 'Create Article'%>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% if @article.image.attachment %>
  <%= image_tag @article.image, width: '250' %>
<% end %>
<p><%= @article.body %></p>

<%= form_with model: [@article, Comment.new], local: true do |form| %>
  <%= form.label :comment %>
  <%= form.text_field :body, id: 'comment_comment', placeholder: 'Write a comment' %>
  <%= form.submit value: 'Add Comment'%>
<% end %>

<% if @article.comments.any? %>
  <% @article.comments.each do |comment| %>
    <p><%= comment.body %></p>
  <% end %>
<% end %>

<% if @article.categories.any? %>
  <% @article.categories.each do |category| %>
    <p><%= category.name %></p>
  <% end %>
<% end %>

<%= link_to 'Delete Article', article_path(@article), method: :delete %>
<%= link_to 'Edit Article', edit_article_path(@article) %>

app/views/categories/show.html.erb
<% @category.articles.each do |article| %>
  <p><%= article.title %></p>
  <p><%= article.body %></p>
<% end %>

app/views/index/index.html.erb
<div id='container'>
  <%= link_to_unless_current "English", locale: "en"%>
  <%= link_to_unless_current "Svenska", locale: "sv"%>
</div>

<h1><%= t('header.main')%></h1>

<% @api_news_feed.each do |article|%>
  <article id="news">
    <h1><%=article.title %></h1>
    <p><%=article.description %></p>
  </article>
<% end %>

app/views/layouts/_nav.html.erb
<% Category.all.each do |category| %>
  <%= link_to category.name, category_path(category) %>
<% end %>

<% if user_signed_in? %>
  <li><%= link_to t('navbar.logout'), destroy_user_session_path, method: :delete %></li>
  <li><%= link_to t('navbar.pay'), new_subscription_path%></li>
<% else %>
  <li><%= link_to t('navbar.login'), new_user_session_path %></li>
  <li><%= link_to t('navbar.register'), new_user_registration_path %></li>
<% end %>

<h2><%= link_to t('navbar.write'), new_article_path %></h2>

app/views/layouts/_navbar.html.erb
<% Category.all.each do |category| %>
<%= link_to category.subject, root_path %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="mui--text-light mui--text-display1 mui--align-vertical">NEWS</div>
  <% Category.all.each do |category| %>
    <%= link_to category.name, root_path %>
  <% end %>
  <h1>Domestic</h1>
  <h1>Sports</h1>
  <h1>Fashion</h1>
  <h1>Tech</h1>
  <h1>Business</h1>
  <h1>Culture</h1>
  <h1>Health</h1>
  <h1>Science</h1>
  <h1>Entertainment</h1>
  <h1>World</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dreamteam</title>
    <%= csrf_meta_tags %>
    <% if Rails.env.test? %>
      <%= tag.meta id: :fake_position, content: fake_location %>
    <% end %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-env="<%= Rails.env %>" data-geocoded="<%= @geocoded %>">
    <% flash.each do |key, value| %>
      <%= value %>
    <% end %>

    <%= render 'layouts/nav' %>

    <%= yield %>
  </body>
</html>

app/views/subscriptions/new.html.erb
<%= form_with url: subscriptions_path do %>
  <article>
    <label class="amount">
      <span>Amount: 100sek</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-email="<%= current_user.email %>"
          data-key="<%= Rails.application.credentials.stripe[:stripe_app] %>"
          data-description="A month's subscription"
          data-amount="10000"
          data-currency="SEK"></script>
<% end %>